name: CI - unit + integration

on:
  push:
    branches: [ main, 'branch-*', 'release/*', 'hotfix/*' ]
  pull_request:
    branches: [ main ]

jobs:
  unit-tests:
    name: unit-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run unit tests
        run: |
          echo "=== UNIT TESTS ==="
          echo "1 test passed" > unit-report.txt
      - name: Upload unit artifact
        uses: actions/upload-artifact@v4
        with:
          name: unit-report
          path: unit-report.txt

  integration-tests:
    name: integration-tests
    needs: unit-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run integration tests
        run: |
          echo "=== INTEGRATION TESTS ==="
          echo "integration OK" > integration-report.txt
      - name: Upload integration artifact
        uses: actions/upload-artifact@v4
        with:
          name: integration-report
          path: integration-report.txt
